apiVersion: v1
kind: Service
metadata:
  name: sctp-service
  labels:
    app: sctp-server
spec:
  ports:
    - name: sctp-server
      protocol: SCTP
      port: 55677
      targetPort: 55677
  selector:
    app: sctp-server
  type: ClusterIP
